[package]
name = "sol-middleware-program"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.2.1"
borsh = "1.5.7"
borsh-derive = "1.5.7"
ahash = "0.8.11"


[lib]
name = "sol_middleware_program"
crate-type = ["cdylib", "lib"]
