name: Client SDK Workflow

on:
  workflow_call:

jobs:
  client-sdk:
    name: Build & Publish Rust Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Rust SDK
        run: cargo build --manifest-path clients/rust/Cargo.toml --release

      - name: Test Rust SDK
        run: cargo test --manifest-path clients/rust/Cargo.toml
      - name: Debug GitHub context
        run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.event_name: ${{ github.event_name }}"
    
      - name: Publish to crates.io
        if: github.ref_name == 'master' && github.event_name == 'push'
        run: cargo publish --manifest-path clients/rust/Cargo.toml --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
