name: Client SDK Workflow

on:
  workflow_call:
    inputs:
      level:
        required: false
        type: string
      version:
        required: false
        type: string
      dry_run:
        required: false
        type: string

jobs:
  client-sdk:
    name: Build & Publish Rust Client
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Rust SDK
        run: cargo build --manifest-path clients/rust/Cargo.toml --release

      - name: Test Rust SDK
        run: cargo test --manifest-path clients/rust/Cargo.toml

      - name: Debug GitHub context
        run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.event_name: ${{ github.event_name }}"

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          echo "Publishing crate..."

          if [ "${{ inputs.level }}" == "version" ]; then
            BUMP="${{ inputs.version }}"
          else
            BUMP="${{ inputs.level }}"
          fi

          echo "Release level: $BUMP"

          cargo publish --manifest-path clients/rust/Cargo.toml

      - name: Commit and tag new version
        uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ inputs.dry_run != 'true' }}
        with:
          commit_message: "chore: Release client version"
          tagging_message: "client@v$(date +%Y.%m.%d-%H%M)"
