name: Client SDK Workflow

on:
  workflow_call:
    inputs:
      level:
        required: false
        type: string
        default: "patch"
      dry_run:
        required: false
        type: string
        default: "false"

jobs:
  client-sdk:
    name: Build & Publish Rust Client
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Build SDK
        run: cargo build --manifest-path clients/rust/Cargo.toml --release

      - name: Test SDK
        run: cargo test --manifest-path clients/rust/Cargo.toml

      - name: Bump version and publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cd clients/rust

          if [ "${{ inputs.dry_run }}" = "true" ]; then
            echo "Dry run: version bump simulation only"
            cargo release ${{ inputs.level }} --no-publish --no-push --dry-run
          else
            echo "Executing version bump and publish"
            cargo release ${{ inputs.level }} --execute
          fi
