name: Client SDK Workflow

on:
  workflow_call:

jobs:
  client-sdk:
    name: Build & Publish Rust Client
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Rust SDK
        run: cargo build --manifest-path clients/rust/Cargo.toml --release

      - name: Test Rust SDK
        run: cargo test --manifest-path clients/rust/Cargo.toml

      - name: Debug GitHub context
        run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.event_name: ${{ github.event_name }}"

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          if [ "${{ inputs.level }}" == "version" ]; then
            BUMP=${{ inputs.version }}
          else
            BUMP=${{ inputs.level }}
          fi

          echo "Cargo logging in"
          cargo login $env:CARGO_REGISTRY_TOKEN
          echo "Set email"
          cargo set-git-config --manifest-path clients/rust/Cargo.toml --email ${{ secrets.CARGO_EMAIL }}
          echo "Set name"
          cargo set-git-config --manifest-path clients/rust/Cargo.toml --name ${{ secrets.CARGO_NAME }}
          echo "Cargo bump version"
          cargo set-version --manifest-path clients/rust/Cargo.toml --version ${{ github.event.inputs.version }} --bump $BUMP
          echo "Cargo release"
          cargo publish --manifest-path clients/rust/Cargo.toml --token $env:CARGO_REGISTRY_TOKEN

      - name: Commit and tag new version
        uses: stefanzweifel/git-auto-commit-action@v4
        if: github.event.inputs.dry_run == 'false'
        with:
          commit_message: "chore: Release ${{ env.CLIENT_NAME }} version ${{ env.CLIENT_VERSION }}"
          tagging_message: ${{ env.CLIENT_NAME }}@v${{ env.CLIENT_VERSION }}
