name: Client SDK Workflow

on:
  workflow_call:
  inputs:
      runner-name:
        required: false
        type: string
        default: ubuntu-latest
      crate:
        required: true
        type: string
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: true
jobs:
  client-sdk:
    name: Build & Publish Rust Client
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install rust
        uses: dtolnay/rust-toolchain@stable

      - name: publish to crates.io
        run: cargo xtask publish ${{ inputs.crate }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Commit and tag new version
        uses: stefanzweifel/git-auto-commit-action@v4
        if: github.event.inputs.dry_run == 'false'
        with:
          commit_message: "chore: Release ${{ env.CLIENT_NAME }} version ${{ env.CLIENT_VERSION }}"
          tagging_message: ${{ env.CLIENT_NAME }}@v${{ env.CLIENT_VERSION }}
