name: Client SDK Workflow

on:
  workflow_call:

jobs:
  client-sdk:
    name: Build & Publish Rust Client
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Rust SDK
        run: cargo build --manifest-path clients/rust/Cargo.toml --release

      - name: Test Rust SDK
        run: cargo test --manifest-path clients/rust/Cargo.toml

      - name: Debug GitHub context
        run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.event_name: ${{ github.event_name }}"

      - name: Publish to crates.io
        run: cargo publish --manifest-path clients/rust/Cargo.toml --no-verify --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
