name: Client SDK Workflow

on:
  workflow_call:

jobs:
  client-sdk:
    name: Client SDK (Rust)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Client SDK
        run: cargo build --manifest-path client/Cargo.toml --release

      - name: Test Client SDK
        run: cargo test --manifest-path client/Cargo.toml

      - name: Publish to crates.io
        if: github.ref == 'refs/heads/main'
        run: cargo publish --manifest-path client/Cargo.toml --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
