name: Client SDK Workflow

on:
  workflow_call:

jobs:
  client-sdk:
    name: Build & Publish Rust Client
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Rust SDK
        run: cargo build --manifest-path clients/rust/Cargo.toml --release

      - name: Test Rust SDK
        run: cargo test --manifest-path clients/rust/Cargo.toml

      - name: Debug GitHub context
        run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.event_name: ${{ github.event_name }}"

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          if [ "${{ inputs.level }}" == "version" ]; then
            BUMP=${{ inputs.version }}
          else
            BUMP=${{ inputs.level }}
          fi

          if [ "${{ inputs.dry_run }}" == "false" ]; then
            OPTIONS="--no-push --no-tag --no-confirm --execute"
            git config user.name ${{ env.COMMIT_USER_NAME }}
            git config user.email ${{ env.COMMIT_USER_EMAIL }}
          fi

          echo "Cargo logging in"
          cargo login $env:CARGO_REGISTRY_TOKEN
          echo "Cargo release"
          cargo release $BUMP $OPTIONS

          if [ "${{ inputs.dry_run }}" == "false" ]; then
            git reset --soft HEAD~1
          fi

          CLIENT_NAME=`grep -E '^name\s*=' Cargo.toml | awk -F '"' '{print $2}'`
          CLIENT_VERSION=`grep -E '^version\s*=' Cargo.toml | awk -F '"' '{print $2}'`
          echo CLIENT_NAME="${CLIENT_NAME}" >> $GITHUB_ENV
          echo CLIENT_VERSION="${CLIENT_VERSION}" >> $GITHUB_ENV

      - name: Commit and tag new version
        uses: stefanzweifel/git-auto-commit-action@v4
        if: github.event.inputs.dry_run == 'false'
        with:
          commit_message: "chore: Release ${{ env.CLIENT_NAME }} version ${{ env.CLIENT_VERSION }}"
          tagging_message: ${{ env.CLIENT_NAME }}@v${{ env.CLIENT_VERSION }}
