name: Main Workflow Trigger

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  client-sdk:
    if: needs.changes.outputs.rust_changed == 'true'
    uses: ./.github/workflows/client-sdk.yml
    with:
      level: "patch"
      dry_run: "false"
    secrets: inherit

  changes:
    runs-on: ubuntu-latest
    outputs:
      rust_changed: ${{ steps.check.outputs.rust_changed }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check for changes in Rust SDK
        id: check
        run: |
          echo "Checking if clients/rust changed..."
          if git diff --name-only origin/master...HEAD | grep -q "^clients/rust/"; then
            echo "Rust SDK changed"
            echo "rust_changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes in Rust SDK"
            echo "rust_changed=false" >> $GITHUB_OUTPUT
